using Neighborhood.Services.Application.Invoices.DTOs;
using Neighborhood.Services.Application.Invoices.Services;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Neighborhood.Services.Infrastructure.Services.Invoices
{
    public class InvoicePdfService : IInvoicePdfService
    {
        public byte[] GenerateInvoicePdf(InvoiceResponseDto invoice)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .Text("Invoice")
                        .FontSize(20)
                        .Bold();

                    page.Content().Column(column =>
                    {
                        column.Spacing(8);
                        column.Item().Text($"Invoice ID: {invoice.Id}");
                        column.Item().Text($"Booking ID: {invoice.BookingId}");
                        column.Item().Text($"Customer ID: {invoice.CustomerId}");
                        column.Item().Text($"Technician ID: {invoice.TechnicianId}");
                        column.Item().Text($"Amount: {invoice.Amount:N2}");
                        column.Item().Text($"Tax: {invoice.Tax:N2}");
                        column.Item().Text($"Total: {invoice.TotalAmount:N2}");
                        column.Item().Text($"Status: {invoice.Status}");
                        column.Item().Text($"Issued At: {invoice.IssuedAt:O}");
                        if (invoice.PaidAt.HasValue)
                            column.Item().Text($"Paid At: {invoice.PaidAt:O}");
                        if (invoice.VoidedAt.HasValue)
                            column.Item().Text($"Voided At: {invoice.VoidedAt:O}");
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text($"Generated by Neighborhood Services • {DateTime.UtcNow:O}")
                        .FontColor(Colors.Grey.Medium);
                });
            });

            return document.GeneratePdf();
        }
    }
}
