using MediatR;
using Neighborhood.Services.Application.Bookings.DTOs;

namespace Neighborhood.Services.Application.Bookings.Queries.GetBookingsByRecurringQuery
{
    // The materialized visits generated by a recurring arrangement (real bookings + their status).
    public class GetBookingsByRecurringQuery : IRequest<IEnumerable<BookingSummaryDto>>
    {
        public int RecurringBookingId { get; set; }
    }
}
