import { Injectable, inject } from '@angular/core';
import { Observable, catchError, of } from 'rxjs';
import { HttpErrorResponse } from '@angular/common/http';
import { ApiService } from '../../../core/services/api.service';
import { PagedResult } from '../../../core/models/paged-result.model';
import {
  BookingSummary,
  BookingDetails,
  BookingStatus,
  CreateBooking,
  BookingImage,
  MyBookingSummary,
  TechnicianPricingRange,
  SmartMatchCriteria,
  TechnicianMatchResult,
  DisputeType,
} from '../models/booking.model';

export interface GetMyBookingsParams {
  status?: BookingStatus;
  search?: string;
  page?: number;
  pageSize?: number;
}

@Injectable({
  providedIn: 'root',
})
export class BookingService {
  private readonly api = inject(ApiService);

  /** GET /api/bookings/mine — current user's bookings, paged + optional status filter */
  getMyBookings(params: GetMyBookingsParams = {}): Observable<PagedResult<MyBookingSummary>> {
    const query = new URLSearchParams();
    if (params.status) query.set('status', params.status);
    if (params.search?.trim()) query.set('search', params.search.trim());
    query.set('page', String(params.page ?? 1));
    query.set('pageSize', String(params.pageSize ?? 10));

    return this.api.get<PagedResult<MyBookingSummary>>(`/api/bookings/mine?${query.toString()}`);
  }

  /** GET /api/bookings/{id} — full details for one booking */
  getById(id: number): Observable<BookingDetails> {
    return this.api.get<BookingDetails>(`/api/bookings/${id}`);
  }

  /** GET /api/bookings/recurring/{id} — the visits generated by a recurring arrangement */
  getByRecurring(recurringBookingId: number): Observable<BookingSummary[]> {
    return this.api.get<BookingSummary[]>(`/api/bookings/recurring/${recurringBookingId}`);
  }

  /** POST /api/bookings — direct booking (starts Pending until the technician accepts) */
  create(body: CreateBooking): Observable<{ id: number }> {
    return this.api.post<{ id: number }>('/api/bookings', body);
  }

  /** POST /api/bookings/match — Smart Match: best 1-2 technicians for a category/problem (AI-ranked, rule fallback). */
  smartMatch(body: SmartMatchCriteria): Observable<TechnicianMatchResult> {
    return this.api.post<TechnicianMatchResult>('/api/bookings/match', body);
  }

  /** GET /api/bookings/estimate/{problemTypeId} — optional on-demand price estimate */
  estimate(problemTypeId: number, region?: string | null): Observable<{ estimatedPrice: number }> {
    const q = region?.trim() ? `?region=${encodeURIComponent(region.trim())}` : '';
    return this.api.get<{ estimatedPrice: number }>(`/api/bookings/estimate/${problemTypeId}${q}`);
  }

  /** POST /api/bookings/{id}/cancel */
  cancel(id: number, cancellationReason: string): Observable<boolean> {
    return this.api.post<boolean>(`/api/bookings/${id}/cancel`, { bookingId: id, cancellationReason });
  }

  /** POST /api/bookings/{id}/confirm — customer confirms job done (releases escrow) */
  confirm(id: number): Observable<void> {
    return this.api.post<void>(`/api/bookings/${id}/confirm`, {});
  }

  /** GET /api/bookings/{id}/images — Before/After photos for this booking */
  getImages(id: number): Observable<BookingImage[]> {
    return this.api.get<BookingImage[]>(`/api/bookings/${id}/images`);
  }

  /**
   * GET /api/bookings/tech-pricing-range — the tech's MinPrice/MaxPrice for one problem type.
   * Returns null when the tech hasn't priced this problem type yet (server returns 404).
   */
  getTechPricingRange(technicianId: number, problemTypeId: number): Observable<TechnicianPricingRange | null> {
    return this.api
      .get<TechnicianPricingRange>(
        `/api/bookings/tech-pricing-range?technicianId=${technicianId}&problemTypeId=${problemTypeId}`,
      )
      .pipe(
        catchError((err: HttpErrorResponse) => (err.status === 404 ? of(null) : (() => { throw err; })())),
      );
  }

  /** POST /api/bookings/{id}/accept-quote — customer accepts the tech's quote (holds escrow). */
  acceptQuote(id: number): Observable<void> {
    return this.api.post<void>(`/api/bookings/${id}/accept-quote`, {});
  }

  /** POST /api/bookings/{id}/reject-quote — customer rejects; booking goes back to Pending. */
  rejectQuote(id: number): Observable<void> {
    return this.api.post<void>(`/api/bookings/${id}/reject-quote`, {});
  }

  /** POST /api/bookings/{id}/dispute — raise a dispute (flips booking to Disputed + creates the dispute record). */
  raiseDispute(id: number, disputeType: DisputeType, reason: string): Observable<void> {
    return this.api.post<void>(`/api/bookings/${id}/dispute`, { disputeType, reason });
  }
}
