import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { PagedResult } from '../../../core/models/paged-result.model';
import { BookingSummary, BookingDetails, BookingStatus, CreateBooking } from '../models/booking.model';

export interface GetMyBookingsParams {
  status?: BookingStatus;
  search?: string;
  page?: number;
  pageSize?: number;
}

@Injectable({
  providedIn: 'root',
})
export class BookingService {
  private readonly api = inject(ApiService);

  /** GET /api/bookings/mine — current user's bookings, paged + optional status filter */
  getMyBookings(params: GetMyBookingsParams = {}): Observable<PagedResult<BookingSummary>> {
    const query = new URLSearchParams();
    if (params.status) query.set('status', params.status);
    if (params.search?.trim()) query.set('search', params.search.trim());
    query.set('page', String(params.page ?? 1));
    query.set('pageSize', String(params.pageSize ?? 10));

    return this.api.get<PagedResult<BookingSummary>>(`/api/bookings/mine?${query.toString()}`);
  }

  /** GET /api/bookings/{id} — full details for one booking */
  getById(id: number): Observable<BookingDetails> {
    return this.api.get<BookingDetails>(`/api/bookings/${id}`);
  }

  /** GET /api/bookings/recurring/{id} — the visits generated by a recurring arrangement */
  getByRecurring(recurringBookingId: number): Observable<BookingSummary[]> {
    return this.api.get<BookingSummary[]>(`/api/bookings/recurring/${recurringBookingId}`);
  }

  /** POST /api/bookings — direct booking (starts Pending until the technician accepts) */
  create(body: CreateBooking): Observable<{ id: number }> {
    return this.api.post<{ id: number }>('/api/bookings', body);
  }

  /** GET /api/bookings/estimate/{problemTypeId} — optional on-demand price estimate */
  estimate(problemTypeId: number, region?: string | null): Observable<{ estimatedPrice: number }> {
    const q = region?.trim() ? `?region=${encodeURIComponent(region.trim())}` : '';
    return this.api.get<{ estimatedPrice: number }>(`/api/bookings/estimate/${problemTypeId}${q}`);
  }

  /** POST /api/bookings/{id}/cancel */
  cancel(id: number, cancellationReason: string): Observable<boolean> {
    return this.api.post<boolean>(`/api/bookings/${id}/cancel`, { bookingId: id, cancellationReason });
  }

  /** POST /api/bookings/{id}/confirm — customer confirms job done (releases escrow) */
  confirm(id: number): Observable<void> {
    return this.api.post<void>(`/api/bookings/${id}/confirm`, {});
  }
}
