using Neighborhood.Services.Application.Bookings.DTOs;
using Neighborhood.Services.Application.Shared;
using Neighborhood.Services.Domain.Bookings;
using System;
using System.Collections.Generic;
using System.Text;

namespace Neighborhood.Services.Application.Bookings.Interface
{
    public interface IBookingRepository: IGenericRepository<Booking,int>
    {
        // Staff oversight: every booking, paged, with customer + technician names, filter + search.
        Task<PagedResult<StaffBookingDto>> GetBookingsForStaffPagedAsync(BookingStatus? status, string? search, int page, int pageSize);
        Task<Booking?> GetBookingWithDetailsAsync(int bookingId);
        Task<IEnumerable<Booking>> GetCustomerBookingsAsync(int customerId, bool includeDeleted = false);
        Task<IEnumerable<Booking>> GetTechnicianBookingsAsync(int technicianId);

        // All bookings generated by a recurring arrangement (the materialized visits), oldest first.
        Task<IEnumerable<Booking>> GetByRecurringBookingIdAsync(int recurringBookingId);

        // Paged + optional status filter (used by "my bookings")
        Task<PagedResult<Booking>> GetCustomerBookingsPagedAsync(int customerId, BookingStatus? status, string? search, int page, int pageSize);
        Task<PagedResult<Booking>> GetTechnicianBookingsPagedAsync(int technicianId, BookingStatus? status, string? search, int page, int pageSize);
        Task<IEnumerable<Booking>> GetAllBookingsAsync();  // admin
        Task<Booking?> GetBookingWithImagesAsync(int bookingId);
        Task<IEnumerable<Booking>> GetBookingsByStatusAsync(BookingStatus status);

        Task<Booking?> GetActiveBookingForTechnicianAsync(int technicianId, DateTime scheduledAt);

        // True if the technician has a confirmed booking whose time window overlaps [start, end)
        Task<bool> HasOverlappingConfirmedBookingAsync(int technicianId, DateTime start, DateTime end, int? excludeBookingId = null);

        // The technician's confirmed bookings (with a duration set) starting within [from, to) —
        // their busy windows, for the booking-time picker.
        Task<IEnumerable<Booking>> GetConfirmedBookingsInRangeAsync(int technicianId, DateTime from, DateTime to);

        Task<Booking?> GetBookingWithEscrowAsync(int bookingId);
    }
}
